export const SETACT = 'SETACT';
export const SETHTML = 'SETHTML';
export const SETCSS = 'SETCSS';
export const SETBP = 'SETBP';
export const SETSUMMARY = 'SETSUMMARY';
export const SETEVAL = 'SETEVAL';
export const SETFILTER = 'SETFILTER';
export const SETALLFILTER = 'SETALLFILTER';
export const SETRESULTFILTER = 'SETRESULTFILTER';
export const SETALLRESULTFILTER = 'SETALLRESULTFILTER';
export const SETCURRENTRULE = 'SETCURRENTRULE';
export const SETCURRENTRULERESULTS = 'SETCURRENTRULERESULTS';
export const SETHIGHLIGHTACTIVE = "SETHIGHLIGHTACTIVE";
export const RESET = 'RESET';








